version: "3"
services:
    eventstore:
        image: "eventstore/eventstore"
        ports: 
            - "2113:2113"
        volumes:
            - "./eventstore_data/:/var/lib/eventstore"
        environment:
            - EVENTSTORE_RUN_PROJECTIONS=All

    redis:
        image: "redis:3.2.11-alpine"
        ports:
            - "6379:6379"

    
          
