#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

write_batch_stream:    
    path: /events/{streamId}
    defaults: { _controller: 'App\Application\NewBatchEventController' }
    methods: ['POST']

read_batch_stream:    
    path: /events/{streamId}
    defaults: { _controller: 'App\Application\HistoryEventController' }
    methods: ['GET']