#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

write_batch_stream:    
    path: /events/{streamId}
    defaults: { _controller: 'App\Application\NewBatchEventController' }
    methods: ['POST']

read_batch_stream:    
    path: /events/{streamId}
    defaults: { _controller: 'App\Application\HistoryEventController' }
    methods: ['GET']

request_flight_offers:    
    path: /flights/offers
    defaults: { _controller: 'App\Application\FlightRequestController' }
    methods: ['POST']

visits_list:    
    path: /visits
    defaults: { _controller: 'App\Application\VisitListController' }
    methods: ['GET']

request_overnight_offers:    
    path: /overnight/offers
    defaults: { _controller: 'App\Application\OvernightRequestController' }
    methods: ['POST']